version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    environment:
      - GOOGLE_PROJECT_ID: "fuzzylabs"
    steps:
      - checkout
      - run:
          name: Hugo static build
          command: |
            sudo apt-get install -qq -y hugo
            hugo --config="config.toml" -s hugo -d $PWD/public
      - run:
          name: Install Firebase Tools
          command: npm install --prefix=./firebase-deploy firebase-tools
      - run:
          name: Deploy to Firebase
          command: ./firebase-deploy/node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --project $GOOGLE_PROJECT_ID

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - blog_updates
