version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    environment:
      - GOOGLE_PROJECT_ID: "fuzzylabs"
    steps:
      - checkout
      - run:
          name: Install Hugo
          command: |
            TEMP_DEB="$(mktemp)" &&
            wget -O "$TEMP_DEB" 'https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_0.58.3_Linux-64bit.deb' &&
            sudo dpkg -i "$TEMP_DEB"
            rm -f "$TEMP_DEB"
      - run:
          name: Hugo static build
          command: |
            hugo --config="hugo/config.toml" -s hugo -d $PWD/public
      - run:
          name: Install Firebase Tools
          command: |
            mkdir firebase-deploy
            npm install --prefix=./firebase-deploy firebase-tools
      - run:
          name: Deploy to Firebase
          command: ./firebase-deploy/node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --project $GOOGLE_PROJECT_ID

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
